import cardVideos from '../data/card-videos.json';

/**
 * Long-form channel videos mapped to card pages.
 * Generated by scripts/sync_card_videos.py (do not edit src/data/card-videos.json by hand;
 * edit scripts/card-video-map.json and re-run the sync).
 */
export interface CardVideo {
    videoId: string;
    title: string;
    /** ISO 8601 UTC. Public videos: actual publish time. Scheduled: YouTube publishAt. */
    publishAt: string;
    /** ISO 8601 duration from the YouTube API, e.g. PT6M26S. */
    duration?: string;
    cards: string[];
    description: string;
    kind?: string;
}

export const MAX_VIDEOS_PER_CARD = 3;

const ALL_VIDEOS = cardVideos as CardVideo[];

/** Videos for a card, newest first, capped at MAX_VIDEOS_PER_CARD. */
export function getVideosForCard(slug: string, max = MAX_VIDEOS_PER_CARD): CardVideo[] {
    return ALL_VIDEOS.filter((video) => video.cards.includes(slug))
        .sort((a, b) => Date.parse(b.publishAt) - Date.parse(a.publishAt))
        .slice(0, max);
}

export function youtubeThumbnail(videoId: string): string {
    return `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;
}

export function youtubeWatchUrl(videoId: string): string {
    return `https://www.youtube.com/watch?v=${videoId}`;
}

export function youtubeEmbedUrl(videoId: string): string {
    return `https://www.youtube-nocookie.com/embed/${videoId}`;
}

export function buildVideoObjectJsonLd(video: CardVideo) {
    return {
        '@context': 'https://schema.org',
        '@type': 'VideoObject',
        name: video.title,
        description: video.description,
        thumbnailUrl: [youtubeThumbnail(video.videoId)],
        uploadDate: video.publishAt,
        ...(video.duration ? { duration: video.duration } : {}),
        embedUrl: youtubeEmbedUrl(video.videoId),
        contentUrl: youtubeWatchUrl(video.videoId),
    };
}

/** "6:26" from "PT6M26S". */
export function formatDuration(iso?: string): string | null {
    const match = iso?.match(/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/);
    if (!match) return null;
    const [h, m, s] = match.slice(1).map((part) => Number(part ?? 0));
    const ss = String(s).padStart(2, '0');
    return h > 0 ? `${h}:${String(m).padStart(2, '0')}:${ss}` : `${m}:${ss}`;
}
